In [1]:
import pandas as pd

In [3]:
ratings=[['john',5,5,2,1],['mary',4,5,3,2],['bob',4,4,4,3],['lisa',2,2,4,5],['lee',1,2,3,4],['bakari',2,1,5,5]]

In [4]:
ratings

[['john', 5, 5, 2, 1],
 ['mary', 4, 5, 3, 2],
 ['bob', 4, 4, 4, 3],
 ['lisa', 2, 2, 4, 5],
 ['lee', 1, 2, 3, 4],
 ['bakari', 2, 1, 5, 5]]

In [5]:
type(ratings)

list

In [6]:
ratings[0]

['john', 5, 5, 2, 1]

In [7]:
titles=['User','Jaws','Star Wars','Exorcist','Omen']

In [8]:
titles

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [9]:
movies=pd.DataFrame(ratings,columns=titles)

In [10]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0    john     5          5         2     1
1    mary     4          5         3     2
2     bob     4          4         4     3
3    lisa     2          2         4     5
4     lee     1          2         3     4
5  bakari     2          1         5     5

In [11]:
from sklearn import cluster

In [12]:
data=movies.drop('User',axis=1)

In [13]:
data

Jaws  Star Wars  Exorcist  Omen
0     5          5         2     1
1     4          5         3     2
2     4          4         4     3
3     2          2         4     5
4     1          2         3     4
5     2          1         5     5

In [14]:
k_means=cluster.KMeans(n_clusters=2,max_iter=100,random_state=1)

In [15]:
k_means

KMeans(max_iter=100, n_clusters=2, random_state=1)

In [16]:
k_means.fit(data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(max_iter=100, n_clusters=2, random_state=1)

In [17]:
labels=k_means.labels_

In [18]:
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [19]:
movies

User  Jaws  Star Wars  Exorcist  Omen
0    john     5          5         2     1
1    mary     4          5         3     2
2     bob     4          4         4     3
3    lisa     2          2         4     5
4     lee     1          2         3     4
5  bakari     2          1         5     5

In [20]:
outcome=pd.DataFrame(labels,index=movies.User,columns=['Cluster ID'])

In [21]:
k_means.cluster_centers_

array([[1.66666667, 1.66666667, 4.        , 4.66666667],
       [4.33333333, 4.66666667, 3.        , 2.        ]])

In [22]:
import numpy as np

In [23]:
testData=np.array([[4,5,1,2],[3,2,4,4],[3,2,4,1],[3,2,3,3],[5,4,1,4]])

In [24]:
testData

array([[4, 5, 1, 2],
       [3, 2, 4, 4],
       [3, 2, 4, 1],
       [3, 2, 3, 3],
       [5, 4, 1, 4]])

In [25]:
type(testData)

numpy.ndarray

In [26]:
labels_test=k_means.predict(testData)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KMeans was fitted with feature names
  warnings.warn(


In [27]:
labels_test

array([1, 0, 1, 0, 1], dtype=int32)

In [29]:
userNames=np.array(['magmum','morris','lincon','listaa','wilberforce']).reshape(-1,1)

In [ ]:
labels_test

In [30]:
userNames

array([['magmum'],
       ['morris'],
       ['lincon'],
       ['listaa'],
       ['wilberforce']], dtype='<U11')

In [31]:
userNames.reshape(-1,1)

array([['magmum'],
       ['morris'],
       ['lincon'],
       ['listaa'],
       ['wilberforce']], dtype='<U11')

In [32]:
userNames

array([['magmum'],
       ['morris'],
       ['lincon'],
       ['listaa'],
       ['wilberforce']], dtype='<U11')

In [33]:
labels

array([1, 1, 1, 0, 0, 0], dtype=int32)

In [34]:
labels_test=labels_test.reshape(-1,1)

In [35]:
labels_test

array([[1],
       [0],
       [1],
       [0],
       [1]], dtype=int32)

In [36]:
cols=movies.columns.tolist()

In [37]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen']

In [38]:
cols.append('Cluster ID')

In [39]:
cols

['User', 'Jaws', 'Star Wars', 'Exorcist', 'Omen', 'Cluster ID']

In [40]:
newUsers=pd.DataFrame(np.concatenate((userNames,testData,labels_test),axis=1),columns=cols)

In [41]:
newUsers

User Jaws Star Wars Exorcist Omen Cluster ID
0       magmum    4         5        1    2          1
1       morris    3         2        4    4          0
2       lincon    3         2        4    1          1
3       listaa    3         2        3    3          0
4  wilberforce    5         4        1    4          1